### ISSUE TITLE
預測時取到了 inv_word_index[0] 出現 KeyError 錯誤

### ISSUE THREAD

**Issue by jiazheng0609** [hsuanchia/Image-caption#14]
從這裡發現的: https://github.com/hsuanchia/Image-caption/commit/ed21cebe89aa86deeee05eee35fcb04bfc38fbaf#r50254331
我在用 `model_noatt427_1.h5` 模型來預測 `/content/drive/MyDrive/MSCOCO_2017/val2017/000000050331.jpg` 這張圖片的時候會一直產生錯誤，我懷疑是某狀況會預測到 argmax 會取到 0，造成後面要取 inv_word_index[0] 出現 KeyError 錯誤。

錯誤內容：
```
---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

<ipython-input-43-1fd4d2eb85a0> in <module>()
      5 plt.imshow(test_image)
      6 plt.show()
----> 7 cap = Generate_caption(complete_path, True)
      8 print(cap)

<ipython-input-10-63784f0afb1d> in Generate_caption(img_path, show)
     17     token_cur = np.argmax(decoder_output[0,count_tokens]) #取機率分布最高值的index
     18     #print(token_cur)
---> 19     cur_word = inv_word_index[token_cur] #將label值map回到word
     20     if(cur_word != end):
     21       output_text += " " + cur_word

KeyError: 0


```

[Colab 我用來重現這個 bug 的程式碼區段](https://colab.research.google.com/drive/1ogP1zSQn1XT2rqRzdBQK-_mVi8QGdkfZ#scrollTo=4V5iNV1_FUza)

**Comment by hsuanchia** [comment]
可能解法: 將index以外的數字通通視為 unknown token。但要在VOC裡面多一個token，model也要再train一次，否則會影響model的準確度

**Comment by hsuanchia** [comment]
已解決: index 0 為 < pad > 在tokenize階段已補上oov詞彙 < unk >
