### ISSUE TITLE
BLEU 算法改成用預處理好的feature map

### ISSUE THREAD

**Issue by hsuanchia** [hsuanchia/Image-caption#17]
現在這樣應該是處理好了，但跑的時間依舊要很久，推測原因應該是caption的predict太久，使用的圖片又有5000張，時間預估要大約4小時。使用預處理好的feature map應該還是有加快速度的，只是我們資料有5000他需要跑太久了。
可能暫時就先像我們討論時所說的，先大概用一半的資料來算BLEU，這樣應該只要1~2小時左右就可以有結果了，上次我在NLP上課期間跑大概跑了1個多小時用2600筆資料左右，但那時候還沒有pretrain好的feature map。
[Code](https://colab.research.google.com/drive/1F2k1UUw_ypYZwDnkL2XHhO1QRNWaNObh#scrollTo=F_8KnANK-Q-9&uniqifier=1) 我暫時就先不merge上來了，你們幫我看看我有沒有地方是有bug的。

**Comment by jiazheng0609** [comment]
generate_caption_BLEU 這個 function 裡少接收了一個 model_path 參數。
另外我發現 generate_caption_BLEU 裡面的 code 很多是跟上面的 generate_caption 重複，還是希望不要有做太多重複事情的 code，如果其中一個地方改了還有很多地方也要改。看要怎樣整合比較好。

**Comment by hsuanchia** [comment]
改好了，我是87，generate_caption的function已merge好了，再幫我試看看
[Code](https://colab.research.google.com/drive/1F2k1UUw_ypYZwDnkL2XHhO1QRNWaNObh#scrollTo=F_8KnANK-Q-9)

**Comment by jiazheng0609** [comment]
剛剛跑一跑才發現 evaluate_coco 也被你改掉，原本應該是 def evaluate_coco(generated_json, answer_json): (我改好了)，可是我自己也還試不出 bug-free 的版本就是@@。

**Comment by hsuanchia** [comment]
我evalutate_coco的部分完全沒有動喔，就是你原本的版本，我只有動前面在生generated_json的code，不過我可能真的有不小心改到後面的code抱歉，所以說具體的bug是什麼?是不能跑嗎?

**Comment by jiazheng0609** [comment]
先抓到了一個 bug
get_imgid('000000070765.jpg') 會產生結果 7765
但預期結果要是: 70765

**Comment by jiazheng0609** [comment]
> 所以說具體的bug是什麼?是不能跑嗎?

錯誤訊息會出現：
AssertionError: Results do not correspond to current coco set
這代表是正解 answer_json 和 generated_json 要評估的圖片 id 對不起來。可能是不小心用 val2014 的正解來評估 val2017 預測結果，或是 img_id 塞進 json 之前就抓錯了而造成的。

**Comment by hsuanchia** [comment]
> 先抓到了一個 bug
> get_imgid('000000070765.jpg') 會產生結果 7765
> 但預期結果要是: 70765

這個改好了，[Code](https://colab.research.google.com/drive/1F2k1UUw_ypYZwDnkL2XHhO1QRNWaNObh?usp=sharing) 你再試試看。
至於後面你說的error message應該是上面的這個bug造成的，不過我確認一下，評估的時候是用image_id對到val2017的正確caption吧?可是同一張圖片理論上會有5句正解，那他是怎麼知道要對哪一句?還是他是每一句都對，都去算BLEU之後取平均之類的?

**Comment by jiazheng0609** [comment]
又一個 get_imgid 的 bug，他 return 的 data type 是 str，但後面的 coco 工具會做
set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())) 來比對 img_id 集合吻不吻合
但 getImgIds 裡面是裝 int，annsImgIds 裡面會是裝 str，導致兩個 set 永遠會是空集合。

解決方法：把 get_imgid() 後面改成 return int(id)
再改了這邊這段應該就終於能動了:)

**Comment by jiazheng0609** [comment]
yay 解完 issue close 囉~
